### ISSUE TITLE
Before HOL-Task 2: Provision a Text Analytics API and Exercise-2 Task-1: Run notebook - 03 Claim Classification 

### ISSUE THREAD

**Issue by Karthikkc123** [microsoft/MCW-Analyzing-text-with-Azure-Machine-Learning-and-Cognitive-Services#56]
1. In [Before HOL-Task 2: Provision a Text Analytics API](https://github.com/microsoft/MCW-Analyzing-text-with-Azure-Machine-Learning-and-Cognitive-Services/blob/main/Hands-on%20lab/Before%20the%20HOL%20-%20Analyzing%20text%20with%20Azure%20Machine%20Learning%20and%20Cognitive%20Services.md), for resource **Text Analytics** UI has got updated with new name and logo i.e, **Edge Module – Language Detection (Text Analytics)**. 
Please find the below screenshot:

![image](https://user-images.githubusercontent.com/83394010/144084087-55f9b42e-9f08-4ef3-a523-9af1be60a25f.png)

2. In [Exercise-2 Task-1: Run notebook - 03 Claim Classification](https://github.com/microsoft/MCW-Analyzing-text-with-Azure-Machine-Learning-and-Cognitive-Services/blob/main/Hands-on%20lab/HOL%20step-by%20step%20-%20Analyzing%20text%20with%20Azure%20Machine%20Learning%20and%20Cognitive%20Services.md), while running the notebook cells to **Load the trained model** it's throwing an error mentioned below:
**OSError: SavedModel file does not exist at: ./outputs/final_model.hdf5/{saved_model.pbtxt|saved_model.pb}**
Please find the below screenshot for your reference:

![image](https://user-images.githubusercontent.com/83394010/144085878-ef9eb97a-ebd6-4e12-92d4-6c808e7e4076.png)

**Note**: I have checked the TensorFlow library version. The TensorFlow version is 2.2.0 as given in the Labguide.

![image](https://user-images.githubusercontent.com/83394010/144087356-fe858dd1-1f1f-4b13-b2db-0baff7f6bc32.png)

**Comment by shirolkar** [comment]
@Karthikkc123  Can you please run this code in your notebook and let me know the version number? Thanks.
import h5py
print(h5py.__version__)

**Comment by Karthikkc123** [comment]
@shirolkar Sorry I don't have environment right now to check.
