### ISSUE TITLE
Exercise-2 Task 1: Run notebook - 03 Claim Classification, Tensorflow version mismatch.

### ISSUE THREAD

**Issue by Karthikkc123** [microsoft/MCW-Analyzing-text-with-Azure-Machine-Learning-and-Cognitive-Services#58]
In [Exercise-2 Task 1: Run notebook - 03 Claim Classification](https://github.com/microsoft/MCW-Analyzing-text-with-Azure-Machine-Learning-and-Cognitive-Services/blob/main/Hands-on%20lab/HOL%20step-by%20step%20-%20Analyzing%20text%20with%20Azure%20Machine%20Learning%20and%20Cognitive%20Services.md), while running the first cell of 03 Claim Classification there is an note which is mentioned under step-2.

**Note: Pay attention to the top of the notebook and check the TensorFlow library version. The TensorFlow version should be 2.2.0.**

But I found mismatch with the Tensorflow version: 2.1.0 while performing the lab. Please find the below screenshot for your reference:

![image](https://user-images.githubusercontent.com/83394010/146609653-e9a86bbd-21ce-45a4-a188-e73badfdaa32.png)

**Comment by shirolkar** [comment]
@Karthikkc123 Can you confirm that you completed "Task 6: Setup lab environment" in Before the HOL? This needs to be done before you start working on the notebooks. The point to confirm is that your notebook kernel is Python 3.8 - AzureML. Thanks. Jitendra

**Comment by Karthikkc123** [comment]
Yes @shirolkar , I have performed the Before HOL "Task 6: Setup lab environment". 

**The second point to confirm is that your notebook kernel is Python 3.8 - AzureML.** :

Unable to connect kernel Python 3.8 - AzureML in the Notebook of AML studio.

**Comment by shirolkar** [comment]
@Karthikkc123 Tensorflow 2.2 was installed in azureml_py38 environment. So if you cannot connect to the kernel 3.8 then the tensorflow version can be different. Try launching the notebook from the  Jupyter interface (from the compute section select Jypyter link from your compute instance).

**Comment by Karthikkc123** [comment]
@shirolkar tried with the same from Jupyter interface, still connection failed with kernal.

![image](https://user-images.githubusercontent.com/83394010/146965807-dea61fbb-f44f-4554-88a6-37206e0aa7cf.png)

**Comment by Karthikkc123** [comment]
@shirolkar FYI, I'm able to connect Kernal with Python-3.8 Tensorflow, Python-3.8 PyTorch, Python-3.6 AzureML but unable to connect with Python-3.8 AzureML.

**Comment by shirolkar** [comment]
@Karthikkc123 @DawnmarieDesJardins @timahenning I looked into this issue. Old compute instances, Python-3.8 AzureML works. But if I create a new compute instance, I see the issue reported. This is Azure ML studio regression issue. I will see if anyone has reported this issues or if there are any workarounds to this issue. If not, we need someone in the Microsoft Azure ML / compute instance team to provide an update. Thanks. Jitendra

**Comment by sumitmalik51** [comment]
Hi @shirolkar, we are also raising issues from our side with MS Support. Thanks for the information

**Comment by Karthikkc123** [comment]
Hello @shirolkar, we found workaround from Microsoft support for the issue faced in connecting kernal to Python 3.8 - AzureML in Notebooks of AML studio.

By running the below command in Terminal as a part of [Before HOL - Task 6: Setup lab environment](https://github.com/microsoft/MCW-Analyzing-text-with-Azure-Machine-Learning-and-Cognitive-Services/blob/main/Hands-on%20lab/Before%20the%20HOL%20-%20Analyzing%20text%20with%20Azure%20Machine%20Learning%20and%20Cognitive%20Services.md), we are able to connect Python 3.8 - AzureML.

**pip install ipykernel==6.6.0**

![MicrosoftTeams-image](https://user-images.githubusercontent.com/83394010/147927087-c5c8e6cf-8d3f-4248-8daa-d20714b6aef1.png)

**Comment by Shivashant25** [comment]
Hi @shirolkar We tried executing the notebooks with Python 3.8 - AzureML. But in `03 Claim Classification.ipynb> Load the trained model (cell 26)` We are facing an error `ERROR: OSError: SavedModel file does not exist at: ./outputs/final_model.hdf5/{saved_model.pbtxt|saved_model.pb}`. Please look into this.

![image](https://user-images.githubusercontent.com/81952290/147928071-37d64ac7-ad55-481d-a7da-cecb3464e821.png)
