### ISSUE TITLE
Exercise-4 Task-2

### ISSUE THREAD

**Issue by Karthikkc123** [microsoft/MCW-Analyzing-text-with-Azure-Machine-Learning-and-Cognitive-Services#60]
1. In [Exercise-4 Task-2](https://github.com/microsoft/MCW-Analyzing-text-with-Azure-Machine-Learning-and-Cognitive-Services/blob/main/Hands-on%20lab/HOL%20step-by%20step%20-%20Analyzing%20text%20with%20Azure%20Machine%20Learning%20and%20Cognitive%20Services.md), while running the cells of notebook **05 Cognitive Services.ipynb** instructions to be updated to replace the scoring URL in **classifier_service_scoring_endpoint and summarizer_service_scoring_endpoint**. 

![image](https://user-images.githubusercontent.com/83394010/148022112-fd171f51-570c-4cfe-b326-12051a747aaf.png)

2. Also few screenshots need to be updated in **Exercise-3 Task-2 for creating Automated ML and Exercise-4 Task-1 for Text Analytics as UI got updated.**

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolve with merge of PR #61
