### ISSUE TITLE
learningdownloadcenter 40530 needs correction/updates

### ISSUE THREAD

**Issue by gyssels** [microsoft/MCW-Analyzing-text-with-Azure-Machine-Learning-and-Cognitive-Services#62]
the link on documentation downloaded on (https://learningdownloadcenter.microsoft.com/)  for class **40530G** does not work anymore:

 **https://borntolearn.mslearn.net/mct/general/f/225**

The same docx point this github with different name, text of the link:
**40530: Microsoft Cloud Workshop: Cognitive Services and Deep Learning Repository**

**Comment by timahenning** [comment]
Hi @gyssels, I am a little confused.  Can tell me where the broken link exists in the lab or WDS?

**Comment by DawnmarieDesJardins** [comment]
Hi @gyssels - Thanks for opening the issue.  The outdated link is on the MCT Courseware forum.  I contacted that team; they are in the process of updating that information now.  They said the doc should be updated on the Learning Download Center shortly.

Closing this issue as resolved, have a great day.
