### ISSUE TITLE
issue while runnigng 03 Claim Classification

### ISSUE THREAD

**Issue by sumitmalik51** [microsoft/MCW-Analyzing-text-with-Azure-Machine-Learning-and-Cognitive-Services#68]
Hi,

I am having while running the 3 Claim Classification notebook where the **Upload features and labels to the default blob store** cell is getting stuck without any issue. please check on it on priority as we have a few scheduled labs next week.

![image](https://user-images.githubusercontent.com/45102602/161319756-19adefa9-708f-4db3-8300-6c859147a6e1.png)

**Comment by sumitmalik51** [comment]
@DawnmarieDesJardins , please help to get it prioritize..

**Comment by sumitmalik51** [comment]
Hi Team,

Update, I tried in a new environment and this particular cell worked fine but a few cells were getting stuck with no error and I have to rerun them to complete the execution. 

We have a new update in AML where python 3.6 is no more supported in jupyter notebooks, so not sure if this is the issue. please have a look into this
![image](https://user-images.githubusercontent.com/45102602/161434203-2c54fc7a-2441-4950-815c-32a78d6c871e.png)

**Comment by shirolkar** [comment]
@sumitmalik51 @DawnmarieDesJardins @timahenning I ran thru the entire notebook on a new compute instance with Python 3.8 - AzureML kernel (that kernel that is saved with the notebook). There was no errors and the notebook worked without any issues. Please make sure that before you load the notebook you follow setup instructions in Before the HOL - Analyzing text with Azure Machine Learning and Cognitive Services.md. When you import the repo, you should see the data folder with claims_data.csv file and the data folder is in the same directory as the 03 Claim Classification notebook. Thanks Jitendra

**Comment by sumitmalik51** [comment]
Hi, Thanks Yes, seems like was a temp issue with AML. I also tried again and it worked fine, closing the issue. 
Thanks
